project:
  type: website
  output-dir: docs

website:
  title: "Mon vestibule"
  description: "C'est peut-être moi"
  announcement:
    icon: cone-striped
    dismissable: false
    content: |
      "Vous lisez une version non finalisée d'un site actuellement en cours d'élaboration"
    type: primary
    position: above-navbar
  site-url: https://alchiba.fr
  repo-url: https://github.com/a-lambda/a-lambda.github.io
  repo-actions: [edit, issue]
  repo-link-target: _blank
  repo-link-rel: noopener noreferrer
  open-graph: true
  page-footer:
    background: '#F7D89C'
    foreground: '#363333'

    border: true
    left: |
      [Créé avec Quarto](https://quarto.org)
    center: |
      &copy; []{#current-year} Alain CORVISIER
  navbar:
    title: Alcor
    search: true
    left:
      - href: index.qmd
        text: Qui-suis-je?
      - href: quarto_website.qmd
        text: Quarto Website
        icon: megaphone
      - href: sql.qmd
        text: SQL
      - href: animate_plot.qmd
        text: Animate Plot
    tools:
      - icon: github
        href: github.com
       
format:
  html:
    axe: true
    theme: [cosmo, styles.scss]
    lang: fr-FR
    #   light: 
    #     - minty
    #     - css/fira-code.css
    #     - light.css
    #   dark: 
    #     - slate
    #     - dark.css
    code-copy: true
    code-link: true
    code-overflow: wrap
    link-external-newwindow: true
    #code-fold: true
    fontsize: 1.1rem
    monofont: Fira Code # font for chunks
    # css: styles.scss
    toc: true
    page-layout: full
    include-after-body:
      - file: assets/scripts/current-year.html

lightbox: true

execute:
  freeze: true



