project:
  type: website
  output-dir: docs

website:
  title: "C'est peut-être moi"
  description: "Mon vestibule"
  site-url: https://alchiba.fr
  repo-url: https://github.com/a-lambda/a-lambda.github.io
  repo-actions: [edit, issue]
  repo-link-target: _blank
  repo-link-rel: noopener noreferrer
  open-graph: true
  page-footer: 
    border: true
    left: |
      [Créé avec Quarto](https://quarto.org)
    center: |
      2026
  navbar:
    title: Alcor
    search: true
    right:
      - href: index.qmd
        text: Qui-suis-je?
      - href: quarto_website.qmd
        text: Quarto Website
        icon: megaphone
      - href: sql.qmd
        text: SQL
      - href: animate_plot.qmd
        text: Animate Plot
    tools:
      - icon: github
        href: github.com
        
format:
  html:
    
    theme: [cosmo, styles.scss]
    lang: fr-FR
    #   light: 
    #     - minty
    #     - css/fira-code.css
    #     - light.css
    #   dark: 
    #     - slate
    #     - dark.css
    code-copy: true
    code-link: true
    code-overflow: wrap
    link-external-newwindow: true
    #code-fold: true
    fontsize: 1.1rem
    monofont: Fira Code # font for chunks
    # css: styles.scss
    toc: true
    page-layout: full



